[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[metadata]
name = catalyst_ngd_wrappers
version = 0.0.1

[options]
install_requires =
    requests
    importlib-metadata; python_version<"3.10"